name: Simple Workflow

# Déclencheurs
on:
  schedule:
    - cron: "0 * * * *"   # Exécution toutes les heures
  workflow_dispatch:       # Exécution manuelle

jobs:
  main_job:
    runs-on: ubuntu-latest   # Exécution sur un environnement Linux

    steps:
      - name: Affichage du premier message
        run: echo "Récupération du code source"

      - name: Affichage du second message
        run: echo "Vérification terminée"
